Bella Vita Pizzeria/Bella Vita Pizzeria/Controllers/CategoryController.cs
using BellaVitaPizzeria.Core.Contracts;
using BellaVitaPizzeria.Core.Models.Category;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bella_Vita_Pizzeria.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly IProductService productService;

        public CategoryController(
            ICategoryService _categoryService, 
            IProductService _productService)
        {
            categoryService = _categoryService;
            productService = _productService;
        }

        [HttpGet]
        public async Task<IActionResult> AllCategories() 
        {
            var model = await categoryService.GetAllCategoriesAsync();

            foreach (var item in model) 
            {
                item.IsInUse = await IsCategoryInUse(item.Name);
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Add() 
        {
            var model = new CategoryFormModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CategoryFormModel model) 
        {
            if (!ModelState.IsValid) 
            {
                return View(model);
            }

            await categoryService.AddAsync(model);

            return RedirectToAction(nameof(AllCategories));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var category = await categoryService.GetByIdAsync(id);

            if (category == null)
            {
                return BadRequest();
            }

            var model = new CategoryFormModel()
            {
                Id = category.Id,
                Name = category.Name,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryFormModel model, int id) 
        {
            var category = await categoryService.GetByIdAsync(id);

            if (category == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid) 
            {
                return View(model);
            }

            await categoryService.EditAsync(model);

            return RedirectToAction(nameof(AllCategories));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await categoryService.GetByIdAsync(id);
            if(category == null)
            {
                return BadRequest();
            }

            bool isInUse = await IsCategoryInUse(category.Name);

            if (isInUse)
            {
                return BadRequest();
            }

            await categoryService.DeleteAsync(id);
            return RedirectToAction(nameof(AllCategories));

        }
        private async Task<bool> IsCategoryInUse(string name) 
        {
            var products = await productService.GetAllProductsAsync();
            var recipes = products.Where(x => x.CategoryName == name);

            if (recipes.Any())
                return true;

            return false;
        }
    }
}

Bella Vita Pizzeria/Bella Vita Pizzeria/Controllers/FavoriteProductController.cs
using BellaVitaPizzeria.Core.Contracts;
using BellaVitaPizzeria.Core.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Bella_Vita_Pizzeria.Controllers
{
    public class FavoriteProductController : BaseController
    {
        private readonly IFavoriteProductService favoriteProductService;
        private readonly IProductService productService;

        public FavoriteProductController(
            IFavoriteProductService _favoriteProductService, 
            IProductService _productService)
        {
            favoriteProductService = _favoriteProductService;
            productService = _productService;
        }

        [HttpGet]
        public async Task<IActionResult> MyFavoriteProducts()
        {
            var model = await favoriteProductService.GetAllUserFavoriteProductsAsync(User.Id());

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddFavoriteProduct(int id)
        {
            var favoriteProducts = await favoriteProductService.GetAllFavoriteProductsAsync();

            if(favoriteProducts.Any(x=> x.ProductId == id && x.UserId==User.Id()))
            {
                return BadRequest();
            }

            var product = await productService.GetByIdAsync(id);

            if(product == null) 
            {
                return BadRequest();
            }

            await favoriteProductService.AddAsync(new FavoriteProductInfoModel
                (
                    id,
                    User.Id(),
                    product));

            return RedirectToAction("Details", "Product", new { id });
        }

        [HttpGet]
        public async Task<IActionResult> RemoveFavoriteProduct(int id) 
        {
            var favoriteProducts = await favoriteProductService.GetAllFavoriteProductsAsync();

            var product = favoriteProducts.FirstOrDefault(x=> x.ProductId == id && x.UserId == User.Id());

            if (product == null) 
            {
                return BadRequest();
            }

            await favoriteProductService.RemoveAsync(id, User.Id());

            return RedirectToAction(nameof(MyFavoriteProducts));
        }
    }
}

Bella Vita Pizzeria/Bella Vita Pizzeria/Controllers/ProductController.cs
using BellaVitaPizzeria.Core.Contracts;
using BellaVitaPizzeria.Core.Models.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Bella_Vita_Pizzeria.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;        
        private readonly IFavoriteProductService favoriteProductService;        
        private readonly IRatingService ratingService;        

        public ProductController(
            IProductService _productService, 
            ICategoryService _categoryService,
            IFavoriteProductService _favoriteProductService,
            IRatingService _ratingService)
        {
            productService = _productService;
            categoryService = _categoryService;
            favoriteProductService = _favoriteProductService;
            ratingService = _ratingService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> AllProducts(string category, int currentPage = 1) 
        {
            var model = await productService.GetProductsForPageAsync(category,currentPage);

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new ProductFormModel()
            {
                Categories = await categoryService.GetAllCategoriesAsync(),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ProductFormModel model)
        {
            if (ModelState.IsValid == false)
            {
                model.Categories = await categoryService.GetAllCategoriesAsync();
                return View(model);
            }

            if (model.ImageFile == null)
            {
                model.Categories = await categoryService.GetAllCategoriesAsync();
                return View(model);
            }

            if (model.ImageFile != null && model.ImageFile.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    model.ImageFile.CopyTo(memoryStream);
                    byte[] imageBytes = memoryStream.ToArray();

                    model.Image = imageBytes;

                    await productService.AddAsync(model);
                }
                return RedirectToAction(nameof(AllProducts));
            }

            model.Categories = await categoryService.GetAllCategoriesAsync();
            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var model = await productService.GetByIdAsync(id);

            if (model == null)
            {
                return BadRequest();
            }

            var favorites = await favoriteProductService.GetAllFavoriteProductsAsync();

            bool isInFavorite = favorites.Any(x => x.UserId == User.Id()) && favorites.Any(x => x.ProductId == id);

            model.IsInUserFavoriteCollection = isInFavorite;

            double averageRating = await ratingService.GetAverageRatingAboutProductAsync(id);

            model.AverageRating = averageRating;

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await productService.GetByIdAsync(id);

            if (product == null)
            {
                return BadRequest();
            }

            if (User.IsInRole("Admin") == false)
            {
                return Unauthorized();
            }

            var allFr = await favoriteProductService.GetAllFavoriteProductsAsync();
            var frToDelete = allFr.Where(x => x.ProductId == id).ToList();

            if (frToDelete.Any())
            {
                foreach (var favorite in frToDelete)
                {
                    await favoriteProductService.RemoveAsync(favorite.ProductId, favorite.UserId);
                }
            }

            var allRat = await ratingService.GetAllRatingsAboutProductAsync(id);
            if (allRat.Any())
            {
                foreach (var rating in allRat)
                {
                    await ratingService.DeleteAsync(rating.ProductId, rating.UserId);
                }
            }

            await productService.DeleteAsync(id);

            return RedirectToAction(nameof(AllProducts));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var product = await productService.GetByIdAsync(id);

            if (product == null)
            {
                return BadRequest();
            }

            var category = await categoryService.GetByNameAsync(product.CategoryName);

            var model = new ProductFormModel()
            {
                Id = product.Id,
                Title = product.Title,
                Description = product.Description,
                MinimumSize = product.MinimumSize,
                MiddleSize = product.MiddleSize,
                MaximumSize = product.MaxmimumSize,
                MinimumPrice = product.MinimumPrice,
                MiddlePrice = product.MiddlePrice,
                MaximumPrice = product.MaximumPrice,
                CategoryId = category.Id,
                Categories = await categoryService.GetAllCategoriesAsync()
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ProductFormModel model, int id)
        {
            var product = await productService.GetByIdAsync(id);

            if (product == null)
            {
                model.Categories = await categoryService.GetAllCategoriesAsync();
                return BadRequest();
            }

            if (model.ImageFile == null)
            {
                model.Image = Convert.FromBase64String(product.Image);
            }

            if (!ModelState.IsValid)
            {
                model.Categories = await categoryService.GetAllCategoriesAsync();
                return View(model);
            }

            if (model.ImageFile != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    model.ImageFile.CopyTo(memoryStream);
                    byte[] imageBytes = memoryStream.ToArray();

                    model.Image = imageBytes;
                }
            }

            await productService.EditAsync(model);

            return RedirectToAction(nameof(AllProducts));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Search(string title) 
        {
            if (string.IsNullOrEmpty(title) == false && title != "" && title != " ") 
            {
                var model = await productService.GetSearchedProductsAsync(title);

                return View(model);
            }

            return RedirectToAction(nameof(AllProducts));
        }
    }
}

Bella Vita Pizzeria/Bella Vita Pizzeria/Controllers/UserController.cs
using BellaVitaPizzeria.Core.Contracts;
using BellaVitaPizzeria.Core.Models;
using BellaVitaPizzeria.Core.Models.Cart;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Bella_Vita_Pizzeria.Controllers
{
    public class UserController : BaseController
    {
        private readonly IProductService productService;
        private readonly ICartService cartService;
        private readonly UserManager<IdentityUser> userManager;

        public UserController(
            IProductService _productService,
            ICartService _cartService,
            UserManager<IdentityUser> _userManager)
        {
            productService = _productService;
            cartService = _cartService;
            userManager = _userManager;
        }

        [HttpGet]
        public async Task<IActionResult> AddToCart(int productId, string size) 
        {
            var product = await productService.GetByIdAsync(productId);

            if (product == null)
            {
                return BadRequest();
            }

            double price = 0;

            if (size == product.MinimumSize) 
            {
                price = product.MinimumPrice;
            }
            else if (size == product.MiddleSize)
            {
                price = product.MiddlePrice;
            }
            else if (size == product.MaxmimumSize)
            {
                price = product.MaximumPrice;
            }


            var model = new PurchaseModel(0,
                product.Title,
                size,
                product.Image,
                1,
                price,
                User.Id());

            try
            {
                await cartService.AddToCartAsync(model);

                return RedirectToAction(nameof(Cart));
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Cart()
        {
            var model = await cartService.GetPurchasesAsync(User.Id());

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ChangeQuantity(int id,string operation) 
        {
            await cartService.ChangeQuantityAsync(id, operation);

            return RedirectToAction(nameof(Cart));
        }

        [HttpGet]
        public async Task<IActionResult> DeletePurchase(int id) 
        {
            await cartService.DeletePurchaseAsync(id, User.Id());

            return RedirectToAction(nameof(Cart));
        }

        [HttpGet]
        public async Task<IActionResult> Checkout() 
        {
            var model = new OrderFormModel();

            model.Email = userManager.FindByIdAsync(User.Id()).Result.Email;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(OrderFormModel model)
        {
            if (!ModelState.IsValid) 
            {
                return View(model);
            }

            model.UserId = User.Id();

            await cartService.AddOrderAsync(model);

            return RedirectToAction(nameof(Cart));
        }

        [HttpGet]
        public async Task<IActionResult> CompleteOrder(int id) 
        {
            await cartService.DeleteOrderAsync(id);

            return RedirectToAction("Index","Home");
        }
    }
}

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bella Vita Pizzeria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bella_Vita_Pizzeria.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: white;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Admin" asp-action="AllUsers">
                    <img src="~/images/Logo.png" style="width: 130px" alt="Image"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    <ul class="navbar-nav flex-grow-1" >  
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark fw-bold" style="font-size: 20px;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                View
                            </a>
                            <ul class="dropdown-menu">
                                <a class="nav-link text-dark fw-bold" style="font-size: 20px;" asp-controller="Admin" asp-action="AllUsers">Users</a>
                                <a class="nav-link text-dark fw-bold" style="font-size: 20px;" asp-controller="Admin" asp-action="AllRoles">Roles</a>
                                <a class="nav-link text-dark fw-bold" style="font-size: 20px;" asp-controller="Product" asp-action="AllProducts">Products</a>
                                <a class="nav-link text-dark fw-bold" style="font-size: 20px;" asp-controller="Category" asp-action="AllCategories">Categories</a>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark fw-bold" style="font-size: 20px;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Add
                            </a>
                            <ul class="dropdown-menu">
                                <a class="nav-link text-dark fw-bold" style="font-size: 20px;" asp-controller="Admin" asp-action="AddRole">Role</a>
                                <a class="nav-link text-dark fw-bold" style="font-size: 20px;" asp-controller="Product" asp-action="Add">Product</a>
                                <a class="nav-link text-dark fw-bold" style="font-size: 20px;" asp-controller="Category" asp-action="Add">Category</a>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" style="font-size: 20px;" asp-controller="Admin" asp-action="Orders">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" style="font-size: 20px;" asp-controller="Admin" asp-action="GetStatistics">Statistics</a>
                        </li>                                             
                    </ul>
                    <partial name="_AdminMenuPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Bella Vita Pizzeria
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
    <li class="nav-item">
        <form  class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
            <button  type="submit" class="nav-link btn btn-link text-dark">Logout</button>
        </form>
    </li>
    }
    else
    {
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-dark fw-bold" style="font-size: 20px;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="~/images/profile.png" style="width: 30px; height: 30px" />
        </a>
        <ul class="dropdown-menu">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
            </li>
        </ul>
    </li>    
    }
</ul>

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Shared/_Layout.cshtml
@inject ICategoryService categoryService

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bella Vita Pizzeria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bella_Vita_Pizzeria.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: white;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/images/Logo.png" style="width: 130px" alt="Image"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    <ul class="navbar-nav flex-grow-1" >                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark fw-bold" style="font-size: 20px;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Menu
                            </a>
                            <ul class="dropdown-menu">
                                @{
                                    var categories = await categoryService.GetAllCategoriesAsync();
                                    var listCateg = categories.ToList();

                                    for (int i = 0; i < listCateg.Count(); i++)
                                    {
                                        var imageSrc = listCateg[i].Name + ".jfif";

                                        <li class="nav-item">
                                            <a asp-action="AllProducts" asp-controller="Product" asp-route-category="@listCateg[i].Name" class="nav-link text-dark">
                                                <img src="~/images/categories/@imageSrc" alt="Image" style="width: 3rem; height: 3rem;">
                                                <h5 class="card-title mt-1">@listCateg[i].Name</h5>
                                            </a>
                                        </li>
                                    }
                                }                                
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" style="font-size: 20px;" asp-controller="Home" asp-action="AboutUs">About us</a>
                        </li>
                                             
                    </ul>
                    <partial name="_MenuPartial" />                    
                </div>
            </div>
        </nav>
        <div id="searchForm">
            <h3 class="text-center">Search</h3>
            ﻿<div class="text-center">
                <input id="searchInput" type="text" placeholder="Enter title..">                
                <a id="searchLink" class="btn btn-success">Search</a>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Bella Vita Pizzeria
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
    <li class="nav-item">
        <button class="searchButton" onclick="searchForm()">
            <img src="~/images/magnifier.png" style="width: 30px; height: 30px" />
        </button>
    </li>
    @if (SignInManager.IsSignedIn(User))
    {
    <li class="nav-item">
        <a class="nav-link text-dark" asp-action="MyFavoriteProducts" asp-controller="FavoriteProduct">
            <img src="~/images/heart.png" style="width: 30px; height: 30px"/>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-action="Cart" asp-controller="User">
            <img src="~/images/shopping_cart.png" style="width: 30px; height: 30px" />
        </a>
    </li>
    <li class="nav-item">
        <form  class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
            <button  type="submit" class="nav-link btn btn-link text-dark">Logout</button>
        </form>
    </li>
    }
    else
    {
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-dark fw-bold" style="font-size: 20px;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="~/images/profile.png" style="width: 30px; height: 30px" />
        </a>
        <ul class="dropdown-menu">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
            </li>
        </ul>
    </li>    
    }
</ul>

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Shared/_PageBannerPartial.cshtml
@model string

<figure class="image">
    <img src="~/images/Details_Banner.png" alt="background">
    <h2>
        @Model
    </h2>
</figure>

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Shared/_ProductInfoPartial.cshtml
@model ProductInfoModel


<a asp-controller="Product" asp-action="Details" asp-route-id="@Model.Id" class="nav-link text-dark">
    <h5 class="card-title mt-1">@Model.Title</h5>
    <img class="card-img-top" src="data:image/png;base64,@Model.Image" alt="Image" style="width: 250px; height: 150px;">
    @if (Model.Description != null && !string.IsNullOrEmpty(Model.Description))
    {
        <p class="mb-0">@Model.Description</p>
        if (Model.MaxmimumSize != null && string.IsNullOrEmpty(Model.MaxmimumSize) == false && Model.MaxmimumSize != "")
        {
            <p class="mb-0"><span class="fw-bold" style="color: red; font-size:25px;">@Model.MinimumPrice - @Model.MaximumPrice lv.</span></p>
        }
        if (Model.MaxmimumSize == null || string.IsNullOrEmpty(Model.MaxmimumSize) || Model.MaxmimumSize == "")
        {
            <p class="mb-0"><span class="fw-bold" style="color: red; font-size:25px;">@Model.MinimumPrice lv.</span></p>
        }
    }
</a>

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Shared/_RatingPartial.cshtml
@model RatingFormModel

@for(int i = 1;i<=5;i++)
{    
    string imageText = i + ".png";
    string label = $"Rate with {i} star";

    <div class="text-center">
        <img src="~/images/stars/@imageText" class="rounded mx-auto d-block" style="width: 500px;" alt="Image" />
        <input asp-route-value="@i" asp-route-productId="@Model.ProductId" class="btn btn-info" type="submit" value=@label />
    </div>
}