Bella Vita Pizzeria/Bella Vita Pizzeria/Controllers/ProductController.cs
using BellaVitaPizzeria.Core.Contracts;
using BellaVitaPizzeria.Core.Models.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Bella_Vita_Pizzeria.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;        
        private readonly IFavoriteProductService favoriteProductService;        
        private readonly IRatingService ratingService;        

        public ProductController(
            IProductService _productService, 
            ICategoryService _categoryService,
            IFavoriteProductService _favoriteProductService,
            IRatingService _ratingService)
        {
            productService = _productService;
            categoryService = _categoryService;
            favoriteProductService = _favoriteProductService;
            ratingService = _ratingService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> AllProducts(string category, int currentPage = 1) 
        {
            var model = await productService.GetProductsForPageAsync(category,currentPage);

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new ProductFormModel()
            {
                Categories = await categoryService.GetAllCategoriesAsync(),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ProductFormModel model)
        {
            if (ModelState.IsValid == false)
            {
                model.Categories = await categoryService.GetAllCategoriesAsync();
                return View(model);
            }

            if (model.ImageFile == null)
            {
                model.Categories = await categoryService.GetAllCategoriesAsync();
                return View(model);
            }

            if (model.ImageFile != null && model.ImageFile.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    model.ImageFile.CopyTo(memoryStream);
                    byte[] imageBytes = memoryStream.ToArray();

                    model.Image = imageBytes;

                    await productService.AddAsync(model);
                }
                return RedirectToAction(nameof(AllProducts));
            }

            model.Categories = await categoryService.GetAllCategoriesAsync();
            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var model = await productService.GetByIdAsync(id);

            if (model == null)
            {
                return BadRequest();
            }

            var favorites = await favoriteProductService.GetAllFavoriteProductsAsync();

            bool isInFavorite = favorites.Any(x => x.UserId == User.Id()) && favorites.Any(x => x.ProductId == id);

            model.IsInUserFavoriteCollection = isInFavorite;

            double averageRating = await ratingService.GetAverageRatingAboutProductAsync(id);

            model.AverageRating = averageRating;

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await productService.GetByIdAsync(id);

            if (product == null)
            {
                return BadRequest();
            }

            if (User.IsInRole("Admin") == false)
            {
                return Unauthorized();
            }

            var allFr = await favoriteProductService.GetAllFavoriteProductsAsync();
            var frToDelete = allFr.Where(x => x.ProductId == id).ToList();

            if (frToDelete.Any())
            {
                foreach (var favorite in frToDelete)
                {
                    await favoriteProductService.RemoveAsync(favorite.ProductId, favorite.UserId);
                }
            }

            var allRat = await ratingService.GetAllRatingsAboutProductAsync(id);
            if (allRat.Any())
            {
                foreach (var rating in allRat)
                {
                    await ratingService.DeleteAsync(rating.ProductId, rating.UserId);
                }
            }

            await productService.DeleteAsync(id);

            return RedirectToAction(nameof(AllProducts));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var product = await productService.GetByIdAsync(id);

            if (product == null)
            {
                return BadRequest();
            }

            var category = await categoryService.GetByNameAsync(product.CategoryName);

            var model = new ProductFormModel()
            {
                Id = product.Id,
                Title = product.Title,
                Description = product.Description,
                MinimumSize = product.MinimumSize,
                MiddleSize = product.MiddleSize,
                MaximumSize = product.MaxmimumSize,
                MinimumPrice = product.MinimumPrice,
                MiddlePrice = product.MiddlePrice,
                MaximumPrice = product.MaximumPrice,
                CategoryId = category.Id,
                Categories = await categoryService.GetAllCategoriesAsync()
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ProductFormModel model, int id)
        {
            var product = await productService.GetByIdAsync(id);

            if (product == null)
            {
                model.Categories = await categoryService.GetAllCategoriesAsync();
                return BadRequest();
            }

            if (model.ImageFile == null)
            {
                model.Image = Convert.FromBase64String(product.Image);
            }

            if (!ModelState.IsValid)
            {
                model.Categories = await categoryService.GetAllCategoriesAsync();
                return View(model);
            }

            if (model.ImageFile != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    model.ImageFile.CopyTo(memoryStream);
                    byte[] imageBytes = memoryStream.ToArray();

                    model.Image = imageBytes;
                }
            }

            await productService.EditAsync(model);

            return RedirectToAction(nameof(AllProducts));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Search(string title) 
        {
            if (string.IsNullOrEmpty(title) == false && title != "" && title != " ") 
            {
                var model = await productService.GetSearchedProductsAsync(title);

                return View(model);
            }

            return RedirectToAction(nameof(AllProducts));
        }
    }
}

Bella Vita Pizzeria/Bella Vita Pizzeria/Controllers/RatingController.cs
using BellaVitaPizzeria.Core.Contracts;
using BellaVitaPizzeria.Core.Models.Rating;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Bella_Vita_Pizzeria.Controllers
{
    public class RatingController : BaseController
    {
        private readonly IRatingService ratingService;
        private readonly IProductService productService;

        public RatingController(
            IRatingService _ratingService, 
            IProductService _productService)
        {
            ratingService = _ratingService;
            productService = _productService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetAllRatings(int productId)
        {
            var product = await productService.GetByIdAsync(productId);

            if (product == null)
            {
                return NotFound();
            }

            var model = await ratingService.GetAllRatingsAboutProductAsync(productId);

            if (model.Count() == 0)
            {
                return RedirectToAction("Details", "Product", new { id = productId });
            }

            model.All(x => x.ProductTitle == product.Title);

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Add(int productId)
        {
            var product = await productService.GetByIdAsync(productId);

            if (product == null)
            {
                return NotFound();
            }

            var model = new RatingFormModel()
            {
                ProductId = productId,
                Value = 0,
                UserId = User.Id()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(RatingFormModel model, int productId)
        {
            model.UserId = User.Id();

            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var product = await productService.GetByIdAsync(productId);

            if (product == null)
            {
                return NotFound();
            }

            var products = await ratingService.GetAllRatingsAboutProductAsync(productId);

            if (products.Any(x => x.UserId == User.Id()))
            {
                return BadRequest();
            }

            await ratingService.AddAsync(model);

            return RedirectToAction(nameof(GetAllRatings), new { productId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int productId)
        {
            var allRatings = await ratingService.GetAllRatingsAboutProductAsync(productId);

            if (!allRatings.Any())
            {
                return BadRequest();
            }

            var product = allRatings.FirstOrDefault(x => x.UserId == User.Id() && x.ProductId == productId);

            if (product == null)
            {
                return BadRequest();
            }

            if (product.UserId != User.Id())
            {
                return Unauthorized();
            }

            var model = new RatingFormModel()
            {
                ProductId = productId,
                UserId = User.Id(),
                Value = product.Value
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RatingFormModel model, int productId)
        {
            var allRatings = await ratingService.GetAllRatingsAboutProductAsync(productId);

            if (!allRatings.Any())
            {
                return BadRequest();
            }

            var product = allRatings.FirstOrDefault(x => x.UserId == User.Id() && x.ProductId == productId);

            if (product == null)
            {
                return BadRequest();
            }

            if (product.UserId != User.Id())
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                model.UserId = User.Id();
                model.ProductId = productId;
                return View(model);
            }

            model.UserId = User.Id();
            await ratingService.EditAsync(model);

            return RedirectToAction(nameof(GetAllRatings), new { productId });
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteRating(int productId, string userId)
        {
            var rating = await ratingService.GetAllRatingsAboutProductAsync(productId);

            if (rating.FirstOrDefault(x => x.UserId == userId) == null)
            {
                return BadRequest();
            }

            if (!User.IsInRole("Admin"))
            {
                return Unauthorized();
            }

            await ratingService.DeleteAsync(productId, userId);

            return RedirectToAction(nameof(GetAllRatings), new { productId });
        }
    }
}

Bella Vita Pizzeria/Bella Vita Pizzeria/Controllers/UserController.cs
using BellaVitaPizzeria.Core.Contracts;
using BellaVitaPizzeria.Core.Models;
using BellaVitaPizzeria.Core.Models.Cart;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Bella_Vita_Pizzeria.Controllers
{
    public class UserController : BaseController
    {
        private readonly IProductService productService;
        private readonly ICartService cartService;
        private readonly UserManager<IdentityUser> userManager;

        public UserController(
            IProductService _productService,
            ICartService _cartService,
            UserManager<IdentityUser> _userManager)
        {
            productService = _productService;
            cartService = _cartService;
            userManager = _userManager;
        }

        [HttpGet]
        public async Task<IActionResult> AddToCart(int productId, string size) 
        {
            var product = await productService.GetByIdAsync(productId);

            if (product == null)
            {
                return BadRequest();
            }

            double price = 0;

            if (size == product.MinimumSize) 
            {
                price = product.MinimumPrice;
            }
            else if (size == product.MiddleSize)
            {
                price = product.MiddlePrice;
            }
            else if (size == product.MaxmimumSize)
            {
                price = product.MaximumPrice;
            }


            var model = new PurchaseModel(0,
                product.Title,
                size,
                product.Image,
                1,
                price,
                User.Id());

            try
            {
                await cartService.AddToCartAsync(model);

                return RedirectToAction(nameof(Cart));
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Cart()
        {
            var model = await cartService.GetPurchasesAsync(User.Id());

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ChangeQuantity(int id,string operation) 
        {
            await cartService.ChangeQuantityAsync(id, operation);

            return RedirectToAction(nameof(Cart));
        }

        [HttpGet]
        public async Task<IActionResult> DeletePurchase(int id) 
        {
            await cartService.DeletePurchaseAsync(id, User.Id());

            return RedirectToAction(nameof(Cart));
        }

        [HttpGet]
        public async Task<IActionResult> Checkout() 
        {
            var model = new OrderFormModel();

            model.Email = userManager.FindByIdAsync(User.Id()).Result.Email;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(OrderFormModel model)
        {
            if (!ModelState.IsValid) 
            {
                return View(model);
            }

            model.UserId = User.Id();

            await cartService.AddOrderAsync(model);

            return RedirectToAction(nameof(Cart));
        }

        [HttpGet]
        public async Task<IActionResult> CompleteOrder(int id) 
        {
            await cartService.DeleteOrderAsync(id);

            return RedirectToAction("Index","Home");
        }
    }
}

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Product/Add.cshtml
@model ProductFormModel
@{
    ViewBag.Title = "Add Product";
    ViewBag.OperationValue = "Add";
}

<h2 class="title">@ViewBag.Title</h2>
<hr />

<form asp-controller="Product" asp-action="Add" method="post" enctype="multipart/form-data">
    <partial name="_ProductPartial" model="@Model" />
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Product/AllProducts.cshtml
@model ProductQueryModel
@{
    ViewBag.Title = "Products";
}

<partial name="_PageBannerPartial" model="@Model.Category" />

@if (Model.Products.Any())
{
    <p class="text-end">Total @Model.Products.Count() products</p>
    <div class="text-center row">
        @foreach (var p in Model.Products)
        {
            <div class="card text-center col-4" style="width: 20rem; ">
                <div class="card-body">
                    <partial name="_ProductInfoPartial" model="@p" />
                </div>
            </div>
        }
    </div>
}
@if (Model.Products.Any() == false)
{
    <h4 class="text-center">No result!</h4>
}

<br>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        @if (Model.CurrentPage > 1)
        {
            <li class="page-item">
                @{
                    int previousPage = Model.CurrentPage - 1;
                }
                <a class="page-link"
                   asp-controller="Product"
                   asp-action="AllProducts"
                   asp-route-currentPage="@previousPage"
                   asp-route-category="@Model.Category">Previous</a>
            </li>
        }
        @for (int i = 1; i <= Model.PagesCount; i++)
        {
            <li class="page-item">
                <a class="page-link"
                   asp-controller="Product"
                   asp-action="AllProducts"
                   asp-route-currentPage="@i"
                   asp-route-category="@Model.Category">
                    @i
                </a>
            </li>
        }
        @if (Model.CurrentPage < Model.PagesCount)
        {
            <li class="page-item">
                @{
                    int nextPage = Model.CurrentPage + 1;
                }
                <a class="page-link"
                   asp-controller="Product"
                   asp-action="AllProducts"
                   asp-route-currentPage="@nextPage"
                   asp-route-category="@Model.Category">
                    Next
                </a>
            </li>
        }
    </ul>
</nav>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Product/Details.cshtml
@using System.Globalization
@using BellaVitaPizzeria.Core.Models.Product

@model ProductInfoModel
@{
    ViewBag.Title = Model.Title;
}

<partial name="_PageBannerPartial" model="@Model.CategoryName" />

<div class="row">
    <div class="card w-100">
        <div class="card-body">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                <div class="col">
                    <img class="img-fluid" src="data:image/png;base64,@Model.Image" alt="Image" style="width: 500px; height: 250px;">
                    <br>
                    @if (User?.Identity?.IsAuthenticated==true && Model.IsInUserFavoriteCollection == false && User?.IsInRole("Admin") == false)
                    {
                        <a asp-controller="FavoriteProduct" asp-action="AddFavoriteProduct" asp-route-id="@Model.Id" style="color: black; text-decoration: none;">
                            <img src="~/images/heart.png" style="width: 30px; height: 30px" />
                            Add to favorites
                        </a>                        
                    }
                    @if (User?.Identity?.IsAuthenticated == true && Model.IsInUserFavoriteCollection == true && User?.IsInRole("Admin") == false)
                    {
                        <a disabled style="color: black; text-decoration: none;">
                            <img src="~/images/heart_red.png" style="width: 30px; height: 30px" />
                            Already added to favorites
                        </a>
                    }
                </div>
                <div class="col">
                    <h3>@Model.Title</h3><br>                    
                    <p class="mb-0">@Model.Description</p><br>

                    @{
                        if (Model.MiddleSize != null && string.IsNullOrEmpty(Model.MiddleSize) == false && Model.MiddleSize != "")
                        {
                            <p class="lh-lg mb-0"><span class="fw-bold">Small(@Model.MinimumSize)</span>...........................................<span class="fw-bold" style="color:red">@Model.MinimumPrice lv.</span> <a asp-controller="User" asp-action="AddToCart" asp-route-productId="@Model.Id" asp-route-size="@Model.MinimumSize" class="btn btn-danger">Buy</a></p>

                            <br>

                            <p class="lh-lg mb-0"><span class="fw-bold">Middle(@Model.MiddleSize)</span>...........................................<span class="fw-bold" style="color:red">@Model.MiddlePrice lv.</span> <a asp-controller="User" asp-action="AddToCart" asp-route-productId="@Model.Id" asp-route-size="@Model.MiddleSize" class="btn btn-danger">Buy</a></p>

                            <br>

                            <p class="lh-lg mb-0"><span class="fw-bold">Family(@Model.MaxmimumSize)</span>...........................................<span class="fw-bold" style="color:red">@Model.MaximumPrice lv.</span> <a asp-controller="User" asp-action="AddToCart" asp-route-productId="@Model.Id" asp-route-size="@Model.MaxmimumSize" class="btn btn-danger">Buy</a></p>
                            <br>
                        }
                        else
                        {
                            <p class="lh-lg mb-0"><span class="fw-bold">@Model.MinimumSize</span>...........................................<span class="fw-bold" style="color:red">@Model.MinimumPrice lv.</span> <a asp-controller="User" asp-action="AddToCart" asp-route-productId="@Model.Id" asp-route-size="@Model.MinimumSize" class="btn btn-danger">Buy</a></p>

                            <br>
                        }
                    }
                </div>                
            </div>            
        </div>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
                <h4>Rating</h4>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Average Rating</h5>
                        @if (Model.AverageRating >= 0 && Model.AverageRating < 1)
                        {
                            <img src="~/images/stars/0.png" class="card-img" alt="Image" />
                        }
                        @if (Model.AverageRating >= 1 && Model.AverageRating < 2)
                        {
                            <img src="~/images/stars/1.png" class="card-img" alt="Image" />
                        }
                        @if (Model.AverageRating >= 2 && Model.AverageRating < 3)
                        {
                            <img src="~/images/stars/2.png" class="card-img" alt="Image" />
                        }
                        @if (Model.AverageRating >= 3 && Model.AverageRating < 4)
                        {
                            <img src="~/images/stars/3.png" class="card-img" alt="Image" />
                        }
                        @if (Model.AverageRating >= 4 && Model.AverageRating < 5)
                        {
                            <img src="~/images/stars/4.png" class="card-img" alt="Image" />
                        }
                        @if (Model.AverageRating == 5)
                        {
                            <img src="~/images/stars/5.png" class="card-img" alt="Image" />
                        }
                        <h3 class="card-text text-center">@Model.AverageRating</h3>
                        @if (Model.AverageRating > 0)
                        {
                            <a asp-controller="Rating" asp-action="GetAllRatings" asp-route-productId="@Model.Id" class="fw-bold">View All Ratings</a>
                        }
                    </div>
                </div>
            </div>
            @{
                if (User?.Identity?.IsAuthenticated == true)
                {
                    if (User?.IsInRole("Admin") == true)
                    {
                        <a asp-controller="Product" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Edit</a>
                        <a asp-controller="Product" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger mb-2 w-100 p-3 fw-bold">Delete</a>
                    }
                    else
                    {
                        <a asp-controller="Rating" asp-action="Add" asp-route-productId="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Rate the @Model.Title</a>
                    }
                }
            }
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Product/Edit.cshtml
@model ProductFormModel
@{
    ViewBag.Title = "Edit Product";
}

<h2 class="title">@ViewBag.Title</h2>
<hr />

<h4 class="text-center">@Model.Title</h4>
<hr />

<form asp-controller="Product" asp-action="Edit" method="post" enctype="multipart/form-data">
    <partial name="_ProductPartial" model="@Model" />
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Bella Vita Pizzeria/Bella Vita Pizzeria/Views/Product/Search.cshtml
@model IEnumerable<ProductInfoModel>
@{
    ViewBag.Title = "Products Result";
}
<h2 class="title">Result</h2>
<hr />

@if (Model.Any())
{
    <p class="text-end">Total @Model.Count() products</p>
    <div class="text-center row">
        @foreach (var p in Model)
        {
            <div class="card text-center col-4" style="width: 20rem; ">
                <div class="card-body">
                    <partial name="_ProductInfoPartial" model="@p" />
                </div>
            </div>
        }
    </div>
}


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}